In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/online-retail-data-set-from-uci-ml-repo/Online Retail.xlsx
/kaggle/input/online-retail-ii-data-set-from-ml-repository/online_retail_II.xlsx

In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (21.0)
Collecting pip
  Downloading pip-21.0.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.2 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0
    Uninstalling pip-21.0:
      Successfully uninstalled pip-21.0
Successfully installed pip-21.0.1

##############################################################
# CLTV Prediction with Gamma-Gamma and BGNBD
##############################################################


# Updated:
# Quote: General comments are same 
# Some developments has been made.
# 1. Monetary simplified.
# 2. freq > 1 reduction has been made.
# 3. Recency personalized. (last purchase date - first purchase date)
# 4. Depending on the previous entry recency has been changed.
# 5. recency_weekly variable's name changed as "recency_weekly_cltv_p".
# 6. As a result general comments and course not changed.


# 4 Steps CLTV

# 1. Data Preperation
# 2. With BG-NBD Model,Expected Sale Forecasting values calculation.
# 3. With Gamma-Gamma Model,Expected Average Profit values calculation.
# 4. With BG-NBD and Gamma-Gamma models calculate specific timeframe's cltv values.


# Formulas:
# CLTV = (Customer_Value / Churn_Rate) x Profit_margin.
# Customer_Value = Average_Order_Value * Purchase_Frequency

##############################################################
# 1. Data Preperation
##############################################################

In [3]:
!pip install lifetimes

Collecting lifetimes
  Downloading Lifetimes-0.11.3-py3-none-any.whl (584 kB)
     |████████████████████████████████| 584 kB 1.3 MB/s
Requirement already satisfied: scipy>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from lifetimes) (1.4.1)
Requirement already satisfied: dill>=0.2.6 in /opt/conda/lib/python3.7/site-packages (from lifetimes) (0.3.3)
Requirement already satisfied: autograd>=1.2.0 in /opt/conda/lib/python3.7/site-packages (from lifetimes) (1.3)
Requirement already satisfied: pandas>=0.24.0 in /opt/conda/lib/python3.7/site-packages (from lifetimes) (1.2.0)
Requirement already satisfied: numpy>=1.10.0 in /opt/conda/lib/python3.7/site-packages (from lifetimes) (1.19.5)
Requirement already satisfied: future>=0.15.2 in /opt/conda/lib/python3.7/site-packages (from autograd>=1.2.0->lifetimes) (0.18.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->lifetimes) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24.0->lifetimes) (2019.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->lifetimes) (1.15.0)
Installing collected packages: lifetimes
Successfully installed lifetimes-0.11.3

In [4]:
import datetime as dt
import matplotlib.pyplot as plt
from lifetimes import BetaGeoFitter
from lifetimes import GammaGammaFitter
from lifetimes.plotting import plot_period_transactions
from sklearn.preprocessing import MinMaxScaler

In [5]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
pd.set_option("display.float_format",lambda x: '%.5f'%x)

In [6]:
def outlier_thresholds(dataframe,variable):
    quartile1=dataframe[variable].quantile(0.01)
    quartile3=dataframe[variable].quantile(0.99)
    interquartile_range=quartile3-quartile1
    up_limit=quartile3 + 1.5 * interquartile_range
    low_limit=quartile1 - 1.5 * interquartile_range
    return low_limit,up_limit

In [7]:
def replace_with_thresholds(dataframe,variable):
    low_limit,up_limit = outlier_thresholds(dataframe,variable)
    #dataframe.loc[(dataframe[variable] < low_limit),variable]=low_limit
    dataframe.loc[(dataframe[variable]>up_limit),variable]=up_limit

In [8]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)
     |████████████████████████████████| 243 kB 1.3 MB/s
Collecting et-xmlfile
  Downloading et_xmlfile-1.0.1.tar.gz (8.4 kB)
Building wheels for collected packages: et-xmlfile
  Building wheel for et-xmlfile (setup.py) ... - \ done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8913 sha256=405163fc8bc5222e70a6e29d6fed2deb40dc473dc011c2ab7df6d105b030195e
  Stored in directory: /root/.cache/pip/wheels/e2/bd/55/048b4fd505716c4c298f42ee02dffd9496bb6d212b266c7f31
Successfully built et-xmlfile
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.0.1 openpyxl-3.0.7

In [9]:
df_=pd.read_excel("/kaggle/input/online-retail-ii-data-set-from-ml-repository/online_retail_II.xlsx",sheet_name="Year 2010-2011")

In [10]:
df=df_.copy()

In [11]:
df.shape
df.info()
df.head()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[ns]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

,count,mean,std,min,25%,50%,75%,max
Quantity,541910.00000,9.55223,218.08096,-80995.00000,1.00000,3.00000,10.00000,80995.00000
Price,541910.00000,4.61114,96.75977,-11062.06000,1.25000,2.08000,4.13000,38970.00000
Customer ID,406830.00000,15287.68416,1713.60307,12346.00000,13953.00000,15152.00000,16791.00000,18287.00000

In [12]:
df.columns
df["Country"].values

array(['United Kingdom', 'United Kingdom', 'United Kingdom', ...,
       'France', 'France', 'France'], dtype=object)

In [13]:
df = df[(df["Country"] == "United Kingdom")]

In [14]:
df.dropna(inplace=True)

In [15]:
df=df[~df["Invoice"].str.contains("C",na=False)]

In [16]:
df=df[df["Quantity"]>0]

In [17]:
replace_with_thresholds(df,"Quantity")

In [18]:
replace_with_thresholds(df,"Price")

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,354345.00000,10.67687,22.07553,1.00000,2.00000,4.00000,12.00000,248.50000
Price,354345.00000,2.81504,2.92055,0.00000,1.25000,1.95000,3.75000,31.56000
Customer ID,354345.00000,15552.43622,1594.54603,12346.00000,14194.00000,15522.00000,16931.00000,18287.00000

In [20]:
df["TotalPrice"]=df["Quantity"]*df["Price"]

In [21]:
df["InvoiceDate"].max()

Timestamp('2011-12-09 12:49:00')

In [22]:
today_date=dt.datetime(2011,12,11)

#############################################
# RFM Table
#############################################

In [23]:
## dynamic recency per customer
rfm=df.groupby("Customer ID").agg({"InvoiceDate":
                                  [lambda date:(date.max()-date.min()).days,
                                   lambda date:(today_date - date.min()).days],
                                  "Invoice":lambda num:num.nunique(),
                                  "TotalPrice":lambda TotalPrice:TotalPrice.sum()})

In [24]:
rfm.columns=rfm.columns.droplevel(0)

In [25]:
## recency_cltv_p
rfm.columns=["recency_cltv_p","T","frequency","monetary"]

In [26]:
##simplyfied monetary_avg
rfm["monetary"]=rfm["monetary"]/rfm["frequency"]

In [27]:
rfm.rename(columns={"monetary":"monetary_avg"},inplace=True)

In [28]:
# for BGNBD calculation of WEEKLY RECENCY and WEEKLY T
## recency_weekly_p
rfm["recency_weekly_p"]=rfm["recency_cltv_p"]/7
rfm["T_weekly"]=rfm["T"]/7

In [29]:
##Check
rfm=rfm[rfm["monetary_avg"]>0]

In [30]:
##freq>1
rfm=rfm[(rfm["frequency"]>1)]
rfm["frequency"]=rfm["frequency"].astype(int)

In [31]:
##############################################################
# 2. BG/NBD Model
##############################################################

In [32]:
bgf=BetaGeoFitter(penalizer_coef=0.001)
bgf.fit(rfm["frequency"],
       rfm["recency_weekly_p"],
       rfm["T_weekly"])

In [33]:
##############################################################
# 3. GAMMA-GAMMA Model
##############################################################


ggf = GammaGammaFitter(penalizer_coef=0.01)
ggf.fit(rfm["frequency"],rfm["monetary_avg"])

In [34]:
###Task 1
##Calculate CLTV for UK customers in 2010-2011
cltv = ggf.customer_lifetime_value(bgf,
                                   rfm['frequency'],
                                   rfm['recency_weekly_p'],
                                   rfm['T_weekly'],
                                   rfm['monetary_avg'],
                                   time=6,  # 6 months
                                   freq="W",  # T's frequency info.
                                   discount_rate=0.01)
cltv.head(20)

Customer ID
12747.00000    1937.04614
12748.00000   12365.79618
12749.00000    3446.01044
12820.00000     631.93933
12822.00000    1612.09665
12823.00000    1095.50846
12826.00000     757.01444
12827.00000    1009.14372
12828.00000    1125.11359
12829.00000      16.11081
12830.00000    4663.11033
12832.00000     765.80585
12836.00000    1749.83590
12838.00000     571.73922
12839.00000    2495.27206
12840.00000    1169.42997
12841.00000    1669.02324
12842.00000    1023.29302
12843.00000     991.50487
12844.00000     566.81490
Name: clv, dtype: float64

In [35]:
cltv=cltv.reset_index()

In [36]:
cltv.sort_values(by="clv",ascending=False)

      Customer ID         clv
2486  18102.00000 85651.01047
589   14096.00000 55650.64677
2184  17450.00000 48533.31011
2213  17511.00000 36797.00673
1804  16684.00000 25083.02541
406   13694.00000 25060.70871
587   14088.00000 25010.05913
1173  15311.00000 23591.38948
133   13089.00000 22927.69296
1057  15061.00000 21123.08206
1485  16000.00000 21110.80764
692   14298.00000 20839.63143
1378  15769.00000 18526.06343
2499  18139.00000 17817.89132
2377  17841.00000 15717.33660
454   13798.00000 14629.74945
2150  17389.00000 14028.56200
2424  17949.00000 13819.55167
1503  16029.00000 13594.32494
139   13098.00000 13449.72336
129   13081.00000 12971.29873
1689  16422.00000 12892.15441
1494  16013.00000 12585.61794
1     12748.00000 12365.79618
881   14680.00000 12306.09122
1414  15838.00000 12151.59139
58    12931.00000 11887.55540
271   13408.00000 11030.54575
447   13777.00000  9818.42926
2296  17675.00000  8391.76156
488   13881.00000  8349.28988
2009  17084.00000  8239.29996
843   14607.00000  8234.01599
1044  15039.00000  7882.28091
1604  16240.00000  7880.68030
1082  15113.00000  7775.11088
2384  17857.00000  7656.04069
1106  15159.00000  7638.76844
560   14031.00000  7334.09227
2173  17428.00000  7135.60193
1116  15189.00000  7091.47720
1384  15786.00000  7031.11604
2021  17107.00000  7001.51317
443   13767.00000  6892.02572
1424  15856.00000  6841.45378
2298  17677.00000  6740.68080
1886  16839.00000  6740.54032
2145  17381.00000  6693.81096
1149  15251.00000  6678.20908
53    12921.00000  6644.92039
1549  16133.00000  6610.12486
572   14051.00000  6597.75468
251   13340.00000  6466.16621
1265  15531.00000  6452.18701
975   14866.00000  6405.75437
1090  15125.00000  6344.95626
817   14547.00000  6257.75292
673   14258.00000  6252.23587
1816  16705.00000  6121.41776
1954  16984.00000  6119.76397
1254  15513.00000  6063.54868
1589  16210.00000  5953.02940
1238  15484.00000  5927.93993
63    12939.00000  5789.06801
2031  17139.00000  5725.53521
987   14895.00000  5702.49192
2121  17340.00000  5656.77870
2329  17735.00000  5632.83229
1246  15498.00000  5551.34171
638   14194.00000  5532.50262
1314  15640.00000  5467.43841
1736  16525.00000  5419.59540
928   14769.00000  5387.22487
1641  16333.00000  5283.17124
127   13078.00000  5262.94499
602   14121.00000  5174.39766
145   13113.00000  5156.61669
42    12901.00000  5150.87966
302   13471.00000  5138.49069
2324  17728.00000  5113.97098
1236  15482.00000  5106.46934
2223  17528.00000  5083.86161
70    12950.00000  5074.41676
603   14125.00000  5063.91352
719   14367.00000  5048.45632
670   14251.00000  5025.03368
2060  17203.00000  4957.58789
336   13536.00000  4867.16210
92    13001.00000  4861.05424
1482  15993.00000  4805.27780
1655  16360.00000  4771.24082
577   14062.00000  4767.94757
986   14893.00000  4717.32182
842   14606.00000  4690.53351
1889  16843.00000  4679.39655
10    12830.00000  4663.11033
1573  16180.00000  4618.31682
822   14554.00000  4604.59978
34    12882.00000  4583.15620
2313  17706.00000  4553.91554
1382  15782.00000  4544.05527
242   13319.00000  4540.18028
1735  16523.00000  4517.94719
1856  16779.00000  4510.25679
1546  16126.00000  4471.28037
1574  16182.00000  4467.40414
1798  16672.00000  4459.34655
1302  15615.00000  4445.65104
2245  17581.00000  4439.56538
2389  17865.00000  4431.04296
44    12906.00000  4402.73262
296   13458.00000  4373.99913
910   14733.00000  4355.54279
684   14286.00000  4329.31102
2165  17416.00000  4259.65675
79    12971.00000  4251.16087
239   13316.00000  4245.70781
574   14056.00000  4229.64850
1224  15444.00000  4205.91656
695   14306.00000  4155.76381
2051  17183.00000  4139.84887
82    12985.00000  4101.17884
1786  16652.00000  4093.06736
538   13985.00000  4022.37594
648   14216.00000  4021.47773
311   13488.00000  4013.56596
1064  15078.00000  3987.03121
2479  18092.00000  3986.11209
1612  16253.00000  3963.07455
1626  16303.00000  3945.63241
134   13090.00000  3926.04417
185   13199.00000  3919.76871
1614  16258.00000  3912.91173
2299  17679.00000  3897.58473
1832  16729.00000  3876.37123
1148  15249.00000  3869.94441
2519  18172.00000  3867.35667
530   13969.00000  3849.49733
875   14667.00000  3845.15841
570   14049.00000  3835.71418
2046  17173.00000  3828.92340
375   13629.00000  3818.27116
2027  17131.00000  3817.19309
1403  15814.00000  3749.09176
1505  16033.00000  3748.02964
1198  15382.00000  3736.72994
1768  16609.00000  3716.92330
2110  17317.00000  3688.94146
383   13644.00000  3682.04880
1971  17017.00000  3674.75943
230   13297.00000  3670.90515
1900  16873.00000  3656.58989
1578  16187.00000  3626.48566
2080  17243.00000  3606.09724
1006  14952.00000  3584.43766
1751  16558.00000  3572.87281
2250  17590.00000  3570.23655
1668  16379.00000  3558.72068
344   13555.00000  3555.29737
1666  16376.00000  3554.75008
1187  15358.00000  3546.18157
101   13018.00000  3543.51558
2153  17396.00000  3526.65689
1790  16656.00000  3508.28993
1103  15152.00000  3507.58446
262   13384.00000  3500.03963
940   14796.00000  3499.97180
1164  15290.00000  3491.33670
1235  15478.00000  3475.32987
1249  15505.00000  3455.00732
327   13521.00000  3448.66369
2     12749.00000  3446.01044
1010  14961.00000  3435.00635
2366  17811.00000  3434.64589
24    12856.00000  3431.50826
993   14904.00000  3427.86069
2302  17686.00000  3405.72346
475   13854.00000  3400.16040
803   14527.00000  3383.53242
2018  17100.00000  3375.45321
1026  15009.00000  3374.58276
1045  15044.00000  3358.58838
158   13139.00000  3357.28024
1118  15194.00000  3355.33890
215   13263.00000  3353.22492
246   13324.00000  3350.28221
1049  15050.00000  3344.68051
596   14110.00000  3329.07675
669   14250.00000  3321.56855
2105  17306.00000  3320.37930
2317  17716.00000  3312.87405
2119  17338.00000  3308.17024
299   13467.00000  3305.20961
1989  17049.00000  3298.08449
199   13225.00000  3289.79902
48    12912.00000  3280.99644
484   13871.00000  3279.30880
614   14145.00000  3258.38667
2172  17426.00000  3248.15400
1099  15144.00000  3246.11383
964   14849.00000  3235.99148
1305  15621.00000  3235.19501
2011  17086.00000  3232.28596
198   13224.00000  3219.72707
412   13709.00000  3218.21949
2487  18109.00000  3209.71149
787   14503.00000  3206.24775
518   13949.00000  3197.42896
2462  18055.00000  3181.34875
1524  16079.00000  3175.87248
286   13435.00000  3172.08692
1115  15187.00000  3165.61275
1102  15150.00000  3161.38906
2279  17651.00000  3157.27523
2177  17434.00000  3154.53424
1230  15465.00000  3138.20304
1925  16923.00000  3136.18125
1003  14944.00000  3129.39533
636   14191.00000  3112.42321
436   13755.00000  3098.74681
1474  15977.00000  3094.52388
1446  15903.00000  3093.36629
1217  15427.00000  3085.89037
1248  15502.00000  3085.87991
1203  15398.00000  3066.61376
1695  16440.00000  3064.50233
1323  15654.00000  3061.05324
2544  18229.00000  3057.97902
717   14360.00000  3052.64053
742   14418.00000  3051.73028
1032  15023.00000  3049.28797
1567  16169.00000  3048.77871
1822  16713.00000  3041.03872
2293  17672.00000  3031.32026
749   14432.00000  3030.73976
2237  17566.00000  3028.83631
2028  17133.00000  3021.71936
2318  17719.00000  3006.95242
612   14140.00000  3006.91285
2256  17602.00000  2994.11986
1295  15601.00000  2982.52889
1131  15218.00000  2979.18792
1511  16041.00000  2972.19788
1860  16790.00000  2954.67006
1839  16746.00000  2951.71784
2540  18223.00000  2949.47673
456   13802.00000  2944.99702
321   13507.00000  2927.89403
789   14505.00000  2923.89245
190   13209.00000  2913.71925
745   14422.00000  2901.72115
761   14456.00000  2894.44341
539   13988.00000  2894.36132
1088  15123.00000  2885.54517
1787  16653.00000  2881.86723
481   13868.00000  2881.33217
1393  15804.00000  2876.93049
689   14292.00000  2875.16496
1334  15676.00000  2867.64710
1341  15694.00000  2862.64924
1848  16767.00000  2860.49815
356   13576.00000  2856.98218
409   13704.00000  2841.29599
1212  15416.00000  2840.30104
2474  18079.00000  2835.66891
138   13097.00000  2834.68534
73    12955.00000  2822.40095
625   14164.00000  2814.50825
591   14101.00000  2809.34104
287   13437.00000  2802.79832
1649  16353.00000  2802.24697
516   13941.00000  2800.75878
1966  17004.00000  2782.22123
608   14132.00000  2779.24195
1460  15948.00000  2777.46653
2345  17768.00000  2775.17109
497   13895.00000  2772.41331
2368  17813.00000  2769.78718
256   13365.00000  2769.21644
703   14329.00000  2769.13330
84    12989.00000  2756.55579
507   13924.00000  2755.29713
548   14004.00000  2746.07209
1873  16814.00000  2742.27799
397   13668.00000  2735.89426
255   13363.00000  2730.48486
258   13373.00000  2730.22909
855   14629.00000  2722.61738
575   14057.00000  2715.56433
140   13102.00000  2710.93380
1645  16347.00000  2709.30745
740   14415.00000  2704.59915
288   13447.00000  2695.09426
2280  17652.00000  2694.69604
1234  15473.00000  2693.77717
69    12949.00000  2693.65465
1537  16107.00000  2689.43163
724   14387.00000  2678.10705
1068  15089.00000  2676.70451
177   13178.00000  2666.17427
1067  15088.00000  2665.75865
365   13596.00000  2660.56816
250   13334.00000  2648.96541
2325  17730.00000  2624.93609
1517  16053.00000  2624.67972
2212  17509.00000  2623.38683
1616  16265.00000  2617.30980
1955  16985.00000  2614.33253
576   14060.00000  2609.00231
1025  15005.00000  2606.25684
1583  16201.00000  2598.86431
592   14102.00000  2598.37987
1522  16070.00000  2595.04615
1994  17061.00000  2588.95504
2109  17315.00000  2588.77650
1159  15274.00000  2586.56424
970   14856.00000  2566.55863
2135  17365.00000  2559.51497
150   13124.00000  2556.76741
809   14535.00000  2543.45259
911   14735.00000  2541.27263
826   14562.00000  2533.55200
2040  17160.00000  2531.55662
276   13418.00000  2530.99974
119   13050.00000  2528.60830
1738  16532.00000  2528.50689
2541  18225.00000  2526.89119
963   14844.00000  2523.09095
2542  18226.00000  2515.13474
2126  17350.00000  2512.18389
1535  16102.00000  2511.62451
335   13534.00000  2506.23903
611   14138.00000  2504.98375
404   13685.00000  2504.23038
14    12839.00000  2495.27206
2530  18198.00000  2492.03211
921   14755.00000  2491.79965
94    13004.00000  2491.14537
1795  16669.00000  2486.92745
828   14567.00000  2486.55761
1357  15727.00000  2482.25937
779   14493.00000  2477.54731
1846  16764.00000  2470.14104
1548  16131.00000  2467.79068
1104  15156.00000  2463.39978
1935  16940.00000  2455.72768
1047  15046.00000  2452.55267
1815  16701.00000  2444.44386
426   13735.00000  2442.94002
1775  16626.00000  2434.15105
2365  17809.00000  2428.23038
402   13680.00000  2414.63394
549   14005.00000  2411.21521
1435  15874.00000  2408.67985
459   13808.00000  2404.94265
615   14146.00000  2404.75121
1394  15805.00000  2395.88547
2148  17387.00000  2395.86473
1563  16161.00000  2392.02338
1876  16818.00000  2389.68974
1354  15719.00000  2388.60021
1070  15093.00000  2387.40142
674   14261.00000  2381.11489
746   14426.00000  2377.59917
1375  15763.00000  2376.11138
1624  16295.00000  2374.30518
853   14626.00000  2365.26689
885   14688.00000  2360.33961
1014  14971.00000  2360.19125
543   13994.00000  2355.71379
220   13269.00000  2354.59488
1244  15494.00000  2353.27975
1077  15105.00000  2351.39569
628   14175.00000  2343.19094
2385  17858.00000  2342.81230
2490  18118.00000  2340.30129
1136  15228.00000  2339.92887
1807  16688.00000  2339.74914
2262  17613.00000  2324.37115
326   13517.00000  2318.58861
437   13756.00000  2316.75326
1581  16191.00000  2305.32243
2154  17397.00000  2304.10665
146   13115.00000  2296.47644
300   13468.00000  2294.00979
217   13266.00000  2291.72950
1814  16700.00000  2290.52536
72    12952.00000  2286.58681
2252  17593.00000  2283.49670
1606  16242.00000  2281.59742
891   14698.00000  2279.70332
254   13362.00000  2274.15494
937   14788.00000  2271.26655
2340  17758.00000  2270.77508
2291  17669.00000  2261.03308
2339  17757.00000  2259.57758
393   13658.00000  2259.24763
2134  17364.00000  2255.92106
897   14709.00000  2253.70727
688   14291.00000  2253.13464
261   13381.00000  2245.07933
284   13431.00000  2238.74463
99    13015.00000  2231.85335
2565  18272.00000  2225.47581
1170  15301.00000  2223.85571
2246  17584.00000  2221.99340
2496  18130.00000  2217.58041
2421  17937.00000  2214.41886
727   14390.00000  2207.69646
2032  17144.00000  2207.09435
694   14305.00000  2200.87146
819   14550.00000  2200.71332
473   13849.00000  2192.22273
1271  15547.00000  2188.03760
366   13599.00000  2187.32005
1041  15034.00000  2186.25932
621   14159.00000  2185.28615
1762  16592.00000  2183.87817
1789  16655.00000  2178.13421
2515  18167.00000  2177.38718
1471  15971.00000  2169.63414
180   13186.00000  2164.41582
1176  15321.00000  2158.00863
97    13013.00000  2153.13777
808   14534.00000  2152.49239
1622  16284.00000  2150.42982
1686  16416.00000  2148.32348
1345  15701.00000  2142.53190
1778  16633.00000  2142.09715
2147  17386.00000  2138.10726
114   13040.00000  2127.05036
1059  15065.00000  2122.20990
1739  16533.00000  2120.96594
661   14235.00000  2119.25878
1827  16722.00000  2117.73461
2238  17567.00000  2114.58304
945   14808.00000  2110.71696
1306  15622.00000  2110.47579
74    12957.00000  2108.97928
1742  16549.00000  2106.28122
2231  17554.00000  2105.67039
892   14700.00000  2103.75690
1821  16712.00000  2101.88351
802   14525.00000  2100.08299
253   13350.00000  2096.04622
421   13726.00000  2094.88593
2346  17769.00000  2093.68887
1274  15555.00000  2090.27629
155   13136.00000  2083.08596
1166  15296.00000  2082.19360
1472  15974.00000  2072.50669
604   14126.00000  2072.25641
1362  15738.00000  2072.09779
26    12867.00000  2070.98987
1386  15791.00000  2070.81703
47    12910.00000  2068.88082
156   13137.00000  2064.49732
1933  16934.00000  2064.20018
1970  17015.00000  2062.97561
977   14868.00000  2062.54870
328   13523.00000  2059.13963
1168  15298.00000  2058.05096
1653  16358.00000  2057.82495
2185  17451.00000  2057.57945
1844  16759.00000  2057.07193
635   14189.00000  2053.81908
1679  16401.00000  2052.82321
178   13183.00000  2050.51085
445   13771.00000  2048.11543
1825  16717.00000  2035.89354
1838  16745.00000  2028.71421
1638  16327.00000  2028.31077
1312  15632.00000  2024.88196
2532  18204.00000  2024.81154
2323  17725.00000  2023.51239
463   13823.00000  2023.13969
2435  17975.00000  2020.23319
610   14135.00000  2015.66040
1165  15291.00000  2009.00973
98    13014.00000  2005.49949
1756  16570.00000  1998.34104
490   13883.00000  1994.88073
1871  16811.00000  1992.90439
2001  17073.00000  1986.02583
489   13882.00000  1985.26639
750   14434.00000  1980.08354
1475  15980.00000  1977.69329
109   13032.00000  1972.62221
2503  18145.00000  1972.53265
683   14285.00000  1968.71361
227   13285.00000  1963.59386
1845  16762.00000  1963.40970
816   14546.00000  1956.92494
1884  16837.00000  1954.39446
873   14664.00000  1951.21261
1418  15845.00000  1950.72726
1931  16931.00000  1948.50618
218   13267.00000  1947.99841
992   14903.00000  1944.93166
168   13159.00000  1938.00657
0     12747.00000  1937.04614
2099  17290.00000  1935.65122
1840  16747.00000  1930.55040
1466  15955.00000  1930.44788
1456  15933.00000  1929.35416
1796  16670.00000  1926.25131
1516  16049.00000  1925.83304
1255  15514.00000  1925.64595
2524  18180.00000  1925.48151
2171  17425.00000  1925.34756
1998  17068.00000  1923.55187
1096  15136.00000  1921.37728
586   14085.00000  1919.68309
2569  18287.00000  1918.12746
2249  17589.00000  1917.81490
914   14739.00000  1915.10761
942   14800.00000  1911.75312
504   13914.00000  1911.56470
176   13174.00000  1908.95097
693   14299.00000  1908.60824
1565  16164.00000  1907.37178
1427  15861.00000  1907.27069
2199  17481.00000  1905.75103
1818  16709.00000  1904.38577
655   14227.00000  1903.50387
633   14180.00000  1901.12989
2167  17419.00000  1900.54927
966   14852.00000  1898.62060
1476  15981.00000  1897.99224
1459  15939.00000  1894.23929
1280  15570.00000  1892.54450
2191  17461.00000  1892.18486
1376  15764.00000  1892.06158
462   13822.00000  1889.41908
1964  17001.00000  1888.56428
2308  17700.00000  1888.28028
1385  15787.00000  1886.04074
219   13268.00000  1885.27719
252   13344.00000  1885.04348
1938  16945.00000  1884.54769
2303  17690.00000  1882.41063
1898  16871.00000  1878.99021
1919  16910.00000  1877.10232
1366  15749.00000  1867.61168
672   14257.00000  1866.62763
2553  18242.00000  1863.80836
278   13421.00000  1863.52712
731   14401.00000  1860.04517
1642  16341.00000  1855.09973
588   14092.00000  1852.94565
2483  18096.00000  1851.50076
289   13448.00000  1850.21501
1713  16474.00000  1846.99367
2014  17091.00000  1844.48651
598   14112.00000  1842.77225
351   13566.00000  1841.47513
1223  15443.00000  1841.15912
553   14019.00000  1840.99677
1263  15529.00000  1840.44182
1562  16160.00000  1839.86499
106   13028.00000  1836.49519
1209  15410.00000  1836.31493
2202  17490.00000  1833.42772
2492  18122.00000  1831.46344
2288  17666.00000  1829.41899
1247  15500.00000  1828.82635
2039  17159.00000  1827.38608
323   13510.00000  1825.43811
1730  16513.00000  1824.59752
184   13198.00000  1820.06107
477   13860.00000  1819.80370
624   14163.00000  1819.34011
805   14530.00000  1819.15264
1092  15129.00000  1818.29278
1241  15491.00000  1811.87920
1436  15877.00000  1810.46813
948   14815.00000  1805.09278
2493  18123.00000  1804.80998
545   13999.00000  1802.03114
2410  17920.00000  1802.01533
1570  16173.00000  1801.60507
1521  16066.00000  1799.87533
1142  15239.00000  1797.10101
1577  16186.00000  1795.33318
1031  15022.00000  1794.03151
1050  15051.00000  1790.14816
1555  16145.00000  1789.98743
1331  15673.00000  1787.97476
1258  15521.00000  1787.93920
1499  16019.00000  1787.25317
995   14907.00000  1786.75549
291   13451.00000  1786.73974
675   14262.00000  1785.71131
2534  18210.00000  1784.33622
1914  16900.00000  1783.95665
2260  17611.00000  1781.88357
2371  17819.00000  1778.89914
1797  16671.00000  1777.48182
64    12940.00000  1775.08614
971   14857.00000  1772.85838
247   13327.00000  1768.36313
632   14179.00000  1766.00129
125   13069.00000  1765.17513
983   14882.00000  1764.18850
887   14691.00000  1762.34476
542   13993.00000  1762.24239
389   13654.00000  1761.39008
1620  16279.00000  1759.73029
2194  17466.00000  1757.43984
1493  16012.00000  1754.95665
2458  18041.00000  1754.58489
1708  16464.00000  1753.88220
2276  17644.00000  1753.09889
962   14842.00000  1751.24959
1178  15330.00000  1750.97184
12    12836.00000  1749.83590
280   13426.00000  1749.57676
827   14565.00000  1748.30930
1990  17050.00000  1747.43254
1801  16678.00000  1745.37190
566   14040.00000  1741.22654
815   14544.00000  1739.02770
961   14841.00000  1739.01688
343   13552.00000  1738.98343
1239  15485.00000  1732.42722
1484  15998.00000  1731.87871
1002  14921.00000  1731.20776
2112  17321.00000  1730.70866
298   13461.00000  1730.51700
61    12936.00000  1726.70225
954   14824.00000  1718.77172
866   14655.00000  1717.41382
651   14221.00000  1717.23878
1993  17059.00000  1715.36824
2007  17082.00000  1715.21763
1560  16156.00000  1714.32805
1146  15245.00000  1713.23303
735   14408.00000  1709.58631
2144  17377.00000  1709.26455
1330  15671.00000  1707.24925
2208  17503.00000  1705.75840
1776  16628.00000  1705.48503
2357  17788.00000  1700.65678
2548  18235.00000  1699.94970
738   14412.00000  1697.65358
318   13500.00000  1693.41996
500   13901.00000  1692.59925
730   14397.00000  1691.80897
1662  16369.00000  1690.76907
1500  16020.00000  1690.28407
482   13869.00000  1689.27397
1630  16311.00000  1687.30346
1269  15544.00000  1686.93259
2272  17633.00000  1686.44699
474   13851.00000  1686.42291
163   13148.00000  1682.77852
2203  17491.00000  1680.17787
282   13429.00000  1679.84482
2309  17702.00000  1678.80208
1349  15708.00000  1678.26730
1432  15867.00000  1676.93479
2019  17101.00000  1673.34368
728   14395.00000  1671.69508
1000  14918.00000  1671.33025
16    12841.00000  1669.02324

In [37]:
rfm_cltv_1_task=rfm.merge(cltv,on="Customer ID",how="left")
scaler=MinMaxScaler(feature_range=(0,100))

In [38]:
scaled1=scaler.fit_transform(rfm_cltv_1_task[["clv"]])

In [39]:
scaled1

array([[ 2.26155667],
       [14.43742008],
       [ 4.02331556],
       ...,
       [ 0.37993369],
       [ 1.1480845 ],
       [ 2.23946858]])

In [40]:
rfm_cltv_1_task["scaled_cltv"]=scaled1

In [41]:
rfm_cltv_1_task[rfm_cltv_1_task["monetary_avg"] >= 1000].sort_values("monetary_avg",ascending=False).head(20)

,Customer ID,recency_cltv_p,T,frequency,monetary_avg,recency_weekly_p,T_weekly,clv,scaled_cltv
587,14088.00000,312,323,13,3859.60154,44.57143,46.14286,25010.05913,29.19996
2486,18102.00000,366,368,60,3584.88775,52.28571,52.57143,85651.01047,100.00000
589,14096.00000,97,102,17,3159.07706,13.85714,14.57143,55650.64677,64.97372
2213,17511.00000,370,374,31,2921.95194,52.85714,53.42857,36797.00673,42.96156
2184,17450.00000,359,368,46,2629.52989,51.28571,52.57143,48533.31011,56.66403
129,13081.00000,359,372,11,2575.62273,51.28571,53.14286,12971.29873,15.14436
1366,15749.00000,97,333,3,2521.44667,13.85714,47.57143,1867.61168,2.18049
1954,16984.00000,41,131,2,2240.67500,5.85714,18.71429,6119.76397,7.14500
1804,16684.00000,353,359,28,2120.04696,50.42857,51.28571,25083.02541,29.28515
1485,16000.00000,0,3,3,2055.78667,0.00000,0.42857,21110.80764,24.64747
1612,16253.00000,188,256,2,1841.93000,26.85714,36.57143,3963.07455,4.62700
2021,17107.00000,244,279,6,1802.57167,34.85714,39.85714,7001.51317,8.17447
881,14680.00000,346,372,16,1791.37031,49.42857,53.14286,12306.09122,14.36771
1626,16303.00000,307,334,3,1786.87667,43.85714,47.71429,3945.63241,4.60664
58,12931.00000,336,358,15,1770.05667,48.00000,51.14286,11887.55540,13.87906
1604,16240.00000,53,78,2,1745.96000,7.57143,11.14286,7880.68030,9.20092
1378,15769.00000,363,372,26,1727.11615,51.85714,53.14286,18526.06343,21.62971
1039,15032.00000,110,367,3,1653.03333,15.71429,52.42857,1099.76268,1.28400
1384,15786.00000,68,115,3,1644.06667,9.71429,16.42857,7031.11604,8.20903
1574,16182.00000,222,295,4,1631.36625,31.71429,42.14286,4467.40414,5.21582

In [42]:
rfm_cltv_1_task[rfm_cltv_1_task["recency_weekly_p"] <= 10].head(20)

,Customer ID,recency_cltv_p,T,frequency,monetary_avg,recency_weekly_p,T_weekly,clv,scaled_cltv
4,12822.00000,16,88,2,474.44000,2.28571,12.57143,1612.09665,1.88217
7,12827.00000,38,45,3,143.38333,5.42857,6.42857,1009.14372,1.17820
9,12829.00000,23,361,2,138.11000,3.28571,51.57143,16.11081,0.01881
11,12832.00000,65,99,2,191.51500,9.28571,14.14286,765.80585,0.89410
20,12845.00000,22,291,4,88.52250,3.14286,41.57143,4.34974,0.00508
24,12856.00000,55,64,6,363.32167,7.85714,9.14286,3431.50826,4.00638
29,12872.00000,38,366,2,299.98500,5.42857,52.28571,55.23347,0.06449
32,12878.00000,29,267,2,427.49500,4.14286,38.14286,186.38245,0.21761
33,12879.00000,47,92,3,191.07333,6.71429,13.14286,913.06575,1.06603
34,12882.00000,24,34,2,731.52000,3.42857,4.85714,4583.15620,5.35097
35,12883.00000,64,90,4,175.86750,9.14286,12.85714,1058.54763,1.23588
36,12885.00000,60,124,3,391.74000,8.57143,17.71429,1508.17991,1.76084
38,12888.00000,41,256,2,177.06000,5.85714,36.57143,123.42198,0.14410
40,12895.00000,44,87,2,186.40000,6.28571,12.42857,771.41959,0.90065
44,12906.00000,66,79,5,583.96200,9.42857,11.28571,4402.73262,5.14032
48,12912.00000,37,41,5,332.46000,5.28571,5.85714,3280.99644,3.83066
55,12925.00000,70,75,2,347.02500,10.00000,10.71429,1648.58580,1.92477
61,12936.00000,61,79,4,265.97500,8.71429,11.28571,1726.70225,2.01597
64,12940.00000,33,88,2,456.77000,4.71429,12.57143,1775.08614,2.07246
70,12950.00000,21,25,3,614.33333,3.00000,3.57143,5074.41676,5.92453

In [43]:
rfm_cltv_1_task.sort_values("scaled_cltv",ascending=False)

      Customer ID  recency_cltv_p    T  frequency  monetary_avg  \
2486  18102.00000             366  368         60    3584.88775
589   14096.00000              97  102         17    3159.07706
2184  17450.00000             359  368         46    2629.52989
2213  17511.00000             370  374         31    2921.95194
1804  16684.00000             353  359         28    2120.04696
406   13694.00000             369  374         50    1267.36260
587   14088.00000             312  323         13    3859.60154
1173  15311.00000             373  374         91     667.59681
133   13089.00000             366  370         97     605.18660
1057  15061.00000             368  373         48    1108.30781
1485  16000.00000               0    3          3    2055.78667
692   14298.00000             352  361         44    1159.85545
1378  15769.00000             363  372         26    1727.11615
2499  18139.00000               0   19          6    1406.39000
2377  17841.00000             371  374        124     328.82234
454   13798.00000             370  373         57     650.51114
2150  17389.00000             330  332         34     928.76485
2424  17949.00000             370  372         45     768.52378
1503  16029.00000             335  374         63     889.76040
139   13098.00000             316  318         28    1031.51571
129   13081.00000             359  372         11    2575.62273
1689  16422.00000             351  370         51     645.54598
1494  16013.00000             367  372         47     672.26766
1     12748.00000             372  374        210     153.82814
881   14680.00000             346  372         16    1791.37031
1414  15838.00000             356  368         19    1494.01605
58    12931.00000             336  358         15    1770.05667
271   13408.00000             371  374         62     453.28194
447   13777.00000             372  374         33     734.88924
2296  17675.00000             366  368         31     657.23484
488   13881.00000             308  312         20     857.97600
2009  17084.00000               0   36          2    1474.87500
843   14607.00000             245  262         14    1021.88643
1044  15039.00000             359  369         47     419.57404
1604  16240.00000              53   78          2    1745.96000
1082  15113.00000              44   55          3    1203.11000
2384  17857.00000             361  366         23     786.66043
1106  15159.00000             359  362         30     608.90833
560   14031.00000             365  373         19     909.83474
2173  17428.00000             368  369         28     615.35964
1116  15189.00000             331  333         41     394.43780
1384  15786.00000              68  115          3    1644.06667
2021  17107.00000             244  279          6    1802.57167
443   13767.00000             371  374         37     463.44014
1424  15856.00000             361  366         27     606.94704
2298  17677.00000             367  369         30     545.44100
1886  16839.00000             360  370         34     488.06912
2145  17381.00000             363  373         29     565.67345
1149  15251.00000             232  242         11     953.18091
53    12921.00000             364  374         37     448.29973
1549  16133.00000             314  319         33     436.65303
572   14051.00000             365  367         23     678.71261
251   13340.00000             231  277          7    1500.09714
1265  15531.00000              22   31          2    1003.72000
975   14866.00000             355  367         12    1169.82667
1090  15125.00000             245  271         15     768.19467
817   14547.00000              50   55          8     500.94250
673   14258.00000             328  338          9    1351.66889
1816  16705.00000             358  359         20     701.74950
1954  16984.00000              41  131          2    2240.67500
1254  15513.00000             340  374         19     769.72526
1589  16210.00000             372  374         18     774.94528
1238  15484.00000              77   79          4     896.50375
63    12939.00000             270  335          8    1435.17188
2031  17139.00000             273  289         12     870.13250
987   14895.00000             282  291         20     556.71600
2121  17340.00000             336  367         11    1122.26364
2329  17735.00000             365  368         19     690.00105
1246  15498.00000             364  367         27     493.20000
638   14194.00000             303  309         21     540.45333
1314  15640.00000             367  373         15     834.37733
1736  16525.00000             364  367         26     498.51500
928   14769.00000             354  358          8    1333.79500
1641  16333.00000             302  310         22     496.56432
127   13078.00000             363  367         26     484.26385
602   14121.00000              56   60          4     695.03750
145   13113.00000             365  367         24     510.24833
42    12901.00000             261  271         28     351.12589
302   13471.00000              46   48          4     632.89500
2324  17728.00000              82   87          3     958.67000
1236  15482.00000             343  359         12     917.91000
2223  17528.00000              70   72          8     453.56250
70    12950.00000              21   25          3     614.33333
603   14125.00000              67   79          3     913.47667
719   14367.00000             267  277         16     578.84500
670   14251.00000              55   58          5     575.94000
2060  17203.00000              24   61          6     593.97500
336   13536.00000              74   76          7     492.61286
92    13001.00000             322  327         13     755.29385
1482  15993.00000              35   45          7     399.65286
1655  16360.00000              83   89          6     585.42167
577   14062.00000             354  365         12     866.50750
986   14893.00000               2   12          2     618.92500
842   14606.00000             372  374         93     129.96161
1889  16843.00000             284  328         16     636.38375
10    12830.00000             134  172          6     870.88250
1573  16180.00000             152  253          8    1281.77250
822   14554.00000              42   53          4     595.26000
34    12882.00000              24   34          2     731.52000
2313  17706.00000             362  367         17     614.66588
1382  15782.00000              79   90          3     871.58000
242   13319.00000             360  366         26     417.13654
1735  16523.00000             313  316         21     448.49857
1856  16779.00000             364  367         22     483.16909
1546  16126.00000             267  297          4    1571.94250
1574  16182.00000             222  295          4    1631.36625
1798  16672.00000             264  267         20     406.74700
1302  15615.00000             348  360         23     452.16261
2245  17581.00000             371  373         25     428.72640
2389  17865.00000             333  365         20     526.31600
44    12906.00000              66   79          5     583.96200
296   13458.00000             352  360         14     689.04071
910   14733.00000             351  368         12     798.82583
684   14286.00000             219  243          3    1542.91667
2165  17416.00000             251  282          7     984.77429
79    12971.00000             368  373         86     127.04983
239   13316.00000             217  255          4    1342.51625
574   14056.00000             282  285         23     357.15870
1224  15444.00000              31   41          2     709.13000
695   14306.00000              34   86          2    1046.66000
2051  17183.00000              97  106          6     557.88500
82    12985.00000              27   29          2     619.69000
1786  16652.00000             214  274          7     965.67857
538   13985.00000             260  265         15     470.67533
648   14216.00000              34   38          4     459.82500
311   13488.00000             350  368         13     688.45538
1064  15078.00000             361  369         32     304.47219
2479  18092.00000             363  366         11     778.27545
1612  16253.00000             188  256          2    1841.93000
1626  16303.00000             307  334          3    1786.87667
134   13090.00000             364  373         14     636.48714
185   13199.00000             363  367         38     253.21053
1614  16258.00000             173  220          5     980.93600
2299  17679.00000              32   86          2     991.86000
1832  16729.00000             203  242         21     344.75810
1148  15249.00000             224  257         13     514.49692
2519  18172.00000             275  290         20     378.08400
530   13969.00000             357  366         18     493.62389
875   14667.00000             357  369         25     369.64800
570   14049.00000             301  318          4    1410.97250
2046  17173.00000             125  132          8     470.82500
375   13629.00000             315  339         11     708.39636
2027  17131.00000              70   76          5     492.63400
1403  15814.00000              33   51          4     485.23500
1505  16033.00000             364  370         20     440.82000
1198  15382.00000             280  296          6     992.61833
1768  16609.00000             237  253          7     784.78000
2110  17317.00000              43   90          3     776.50333
383   13644.00000              89  106          4     656.06500
1971  17017.00000             369  373         20     434.71300
230   13297.00000              59   68          4     522.46250
1900  16873.00000             359  365          6    1139.45667
1578  16187.00000             252  285         15     460.20333
2080  17243.00000             368  370         26     333.72500
1006  14952.00000             304  365         11     736.31727
1751  16558.00000             365  367         20     416.92450
2250  17590.00000              37   41          3     493.07333
1668  16379.00000              74   79          4     539.35000
344   13555.00000             128  202          4    1037.32000
1666  16376.00000               8   18          2     493.50500
1187  15358.00000             360  366         22     379.41818
101   13018.00000             279  296         28     259.91786
2153  17396.00000             332  372          8     916.35000
1790  16656.00000             342  365         15     530.60533
1103  15152.00000             177  188         13     365.05308
262   13384.00000             147  179          7     593.13286
940   14796.00000             365  367         17     471.91118
1164  15290.00000             354  360         18     441.29000
1235  15478.00000              16   57          2     720.71000
1249  15505.00000             102  156          5     722.19200
327   13521.00000               8   11          3     364.55000
2     12749.00000             209  214          5     814.48800
1010  14961.00000             349  361          9     782.74222
2366  17811.00000             329  334         39     200.96744
24    12856.00000              55   64          6     363.32167
993   14904.00000              23   26          2     505.01750
2302  17686.00000             295  303          7     819.92286
475   13854.00000             356  366         25     324.38080
803   14527.00000             366  370         55     154.70582
2018  17100.00000               0   19          2     485.87000
1026  15009.00000              12   26          3     420.59333
1045  15044.00000             342  363         17     452.95471
158   13139.00000             243  260          7     723.56286
1118  15194.00000             365  369         15     507.20933
215   13263.00000             323  326         35     212.97343
246   13324.00000             324  361         10     712.19500
1049  15050.00000              46   72          3     594.03000
596   14110.00000             263  267         12     473.59583
669   14250.00000              82   90          3     634.68333
2105  17306.00000             342  354         19     395.69316
2317  17716.00000             245  268         11     514.18091
2119  17338.00000             344  362          8     830.49125
299   13467.00000              25   37          2     541.85500
1989  17049.00000             273  276          9     608.12222
199   13225.00000             358  362          7     909.29857
48    12912.00000              37   41          5     332.46000
484   13871.00000             286  309         13     492.55769
614   14145.00000             170  218          4     935.55000
2172  17426.00000             274  283          6     831.15333
1099  15144.00000             304  313         17     387.08471
964   14849.00000             351  374         25     317.22160
1305  15621.00000              17   22          4     323.25750
2011  17086.00000              56   64          6     341.68000
198   13224.00000              91  152          2    1077.97500
412   13709.00000             311  316         13     486.77308
2487  18109.00000             368  370         26     297.02577
787   14503.00000             175  179          6     590.54333
518   13949.00000              91   95          6     404.55333
2462  18055.00000             362  370         10     678.41900
1524  16079.00000              23   41          3     450.66667
286   13435.00000             183  190          7     544.27000
1115  15187.00000             210  213         16     298.57375
1102  15150.00000             251  270         10     531.44700
2279  17651.00000             165  178         10     394.50000
2177  17434.00000              82   86          7     339.11714
1230  15465.00000             349  370         18     408.59000
1925  16923.00000             350  363         19     381.45316
1003  14944.00000             266  297         12     491.68750
636   14191.00000             218  221         13     360.36615
436   13755.00000              59   64          9     240.15000
1474  15977.00000              21   40          2     527.36500
1446  15903.00000             285  296          7     732.39429
1217  15427.00000              13   48          3     494.38000
1248  15502.00000             353  370         12     568.32250
1203  15398.00000              62   79          2     672.76500
1695  16440.00000             206  215          5     728.13400
1323  15654.00000              16   27          2     461.26500
2544  18229.00000             361  374         20     363.84500
717   14360.00000              62   95          4     532.05750
742   14418.00000             104  109          3     642.95333
1032  15023.00000             366  370         11     600.68091
1567  16169.00000              67   76          4     455.74250
1822  16713.00000             347  367         15     460.98267
2293  17672.00000             259  310          2    1589.08500
749   14432.00000              79   90          6     375.91833
2237  17566.00000              17   26          2     450.60500
2028  17133.00000             250  267          7     664.08429
2318  17719.00000             217  256         15     359.73600
612   14140.00000              27   32          2     467.52500
2256  17602.00000             321  325          6     850.49500
1295  15601.00000             361  373         14     484.04000
1131  15218.00000             308  319         11     523.35364
1511  16041.00000             110  142          3     750.81333
1860  16790.00000              34   38          6     257.60333
1839  16746.00000             354  359         18     372.09222
2540  18223.00000             353  359         14     463.18143
456   13802.00000             172  312          3    1533.14000
321   13507.00000             142  146          4     619.79000
789   14505.00000             344  363          8     735.90625
190   13209.00000             331  362          8     736.45125
745   14422.00000             266  268          6     710.60667
761   14456.00000             137  143          9     340.26667
539   13988.00000             234  255          6     689.86333
1088  15123.00000             198  207          2    1099.65500
1787  16653.00000              55   72          2     606.33000
481   13868.00000              31   39          2     476.17750
1393  15804.00000             198  199         13     309.19308
689   14292.00000             275  283          9     541.32556
1334  15676.00000             265  284          3    1142.45667
1341  15694.00000             372  373         14     462.81429
1848  16767.00000             285  317         11     507.32727
356   13576.00000             362  374         18     373.18556
409   13704.00000              83   89          9     256.45111
1212  15416.00000             218  283          4     996.08000
2474  18079.00000             193  239          4     863.68000
138   13097.00000             327  361         10     601.04200
73    12955.00000             266  268         11     432.46909
625   14164.00000              10   81          2     815.88500
591   14101.00000             252  327          6     853.60917
287   13437.00000             175  191          7     485.66714
1649  16353.00000             366  370         23     290.24826
516   13941.00000             350  373          5    1013.90000
1966  17004.00000              46   93          2     706.47000
608   14132.00000             181  184         11     326.00273
1460  15948.00000              35   44          2     477.62000
2345  17768.00000             157  167          3     757.72667
497   13895.00000             136  165          4     648.26750
2368  17813.00000              57   72          5     353.29800
256   13365.00000             184  218          2    1112.68500
703   14329.00000             312  330          7     715.22071
84    12989.00000             361  365         15     413.02400
507   13924.00000              70   73          6     306.47500
548   14004.00000             245  289          7     654.66286
1873  16814.00000             355  370         21     309.95714
397   13668.00000             359  363         21     303.02810
255   13363.00000              26   44          2     477.81000
258   13373.00000             215  277          3    1104.08333
855   14629.00000              43   48          2     479.50500
575   14057.00000             336  361         17     365.76235
140   13102.00000             363  366         24     267.67042
1645  16347.00000              25   37          2     443.82500
740   14415.00000             359  361         13     453.86769
288   13447.00000              12   36          3     376.38000
2280  17652.00000             255  282         12     405.64333
1234  15473.00000              46   61          7     253.02857
69    12949.00000             221  253          8     520.90250
1537  16107.00000             165  184          7     455.80000
724   14387.00000              76  110          3     590.18667
1068  15089.00000             118  129          6     403.47333
177   13178.00000             334  361         11     520.49727
1067  15088.00000              45   68          2     553.31500
365   13596.00000               7   13          2     348.52000
250   13334.00000             223  306          3    1178.94000
2325  17730.00000             323  327         13     407.57538
1517  16053.00000              89  123          2     739.60000
2212  17509.00000               5   64          8     764.39250
1616  16265.00000             355  365          9     601.12444
1955  16985.00000             341  359         10     546.41200
576   14060.00000             368  373         19     323.18000
1025  15005.00000             350  367         28     225.59179
1583  16201.00000             106  110          4     465.86750

In [44]:
##TASK 2
#Calculate cltv for UK customers for 1 and 12 months.
#Analyze highest cltv' for first 10 per month and 12 months is there any difference,and talk about

In [45]:
cltv2_1month = ggf.customer_lifetime_value(bgf,
                                   rfm['frequency'],
                                   rfm['recency_weekly_p'],
                                   rfm['T_weekly'],
                                   rfm['monetary_avg'],
                                   time=1,  # 1 month
                                   freq="W",  # T's frequency info.
                                   discount_rate=0.01)

In [46]:
cltv2_12months=ggf.customer_lifetime_value(bgf,
                                   rfm['frequency'],
                                   rfm['recency_weekly_p'],
                                   rfm['T_weekly'],
                                   rfm['monetary_avg'],
                                   time=12,  # 12 months
                                   freq="W",  # T's frequency info.
                                   discount_rate=0.01)

In [47]:
cltv2_1month.head(10)

Customer ID
12747.00000    336.77883
12748.00000   2148.37567
12749.00000    604.07100
12820.00000    110.12485
12822.00000    286.92234
12823.00000    191.12371
12826.00000    131.66943
12827.00000    181.13361
12828.00000    198.69579
12829.00000      2.80551
Name: clv, dtype: float64

In [48]:
cltv2_12months.head(10)

Customer ID
12747.00000    3698.38114
12748.00000   23623.99689
12749.00000    6538.82768
12820.00000    1204.32622
12822.00000    3029.79454
12823.00000    2085.98885
12826.00000    1444.88055
12827.00000    1888.15775
12828.00000    2124.46518
12829.00000      30.72005
Name: clv, dtype: float64

In [49]:
cltv2_1month=cltv2_1month.reset_index()

In [50]:
cltv2_12months=cltv2_12months.reset_index()

In [51]:
cltv2_1month.sort_values(by="clv",ascending=False).head(20)

      Customer ID         clv
2486  18102.00000 14884.97500
589   14096.00000  9855.87989
2184  17450.00000  8434.76472
2213  17511.00000  6394.32432
1804  16684.00000  4361.05396
587   14088.00000  4355.48526
406   13694.00000  4354.46853
1173  15311.00000  4098.86945
133   13089.00000  3984.05150
1485  16000.00000  3843.97950
1057  15061.00000  3670.42202
692   14298.00000  3622.66892
1378  15769.00000  3219.68422
2499  18139.00000  3219.44827
2377  17841.00000  2730.73198
454   13798.00000  2542.05174
2150  17389.00000  2441.35391
2424  17949.00000  2401.43868
1503  16029.00000  2362.02950
139   13098.00000  2342.03790

In [52]:
cltv2_12months.sort_values(by="clv",ascending=False).head(20)

      Customer ID          clv
2486  18102.00000 163591.12676
589   14096.00000 104900.44292
2184  17450.00000  92694.27482
2213  17511.00000  70285.65230
1804  16684.00000  47890.36421
406   13694.00000  47871.90000
587   14088.00000  47688.86365
1173  15311.00000  45067.80939
133   13089.00000  43795.47286
1057  15061.00000  40348.81669
692   14298.00000  39793.98592
1485  16000.00000  39238.24976
1378  15769.00000  35383.28606
2499  18139.00000  33232.95645
2377  17841.00000  30026.20445
454   13798.00000  27945.99645
2150  17389.00000  26764.35819
2424  17949.00000  26396.84991
1503  16029.00000  25969.07947
139   13098.00000  25647.76174

In [53]:
rfm_cltv_2_task_1month=rfm.merge(cltv2_1month,on="Customer ID",how="left")

In [54]:
rfm_cltv_2_task_12months=rfm.merge(cltv2_12months,on="Customer ID",how="left")

In [55]:
scaled2_1month=scaler.fit_transform(rfm_cltv_2_task_1month[["clv"]])

In [56]:
scaled2_12months=scaler.fit_transform(rfm_cltv_2_task_12months[["clv"]])

In [57]:
rfm_cltv_2_task_1month["scaled_cltv"]=scaled2_1month

In [58]:
rfm_cltv_2_task_12months["scaled_cltv"]=scaled2_12months

In [59]:
rfm_cltv_2_task_1month.head(20)

,Customer ID,recency_cltv_p,T,frequency,monetary_avg,recency_weekly_p,T_weekly,clv,scaled_cltv
0,12747.00000,366,370,11,381.45545,52.28571,52.85714,336.77883,2.26254
1,12748.00000,372,374,210,153.82814,53.14286,53.42857,2148.37567,14.43318
2,12749.00000,209,214,5,814.48800,29.85714,30.57143,604.07100,4.05826
3,12820.00000,323,327,4,235.58500,46.14286,46.71429,110.12485,0.73984
4,12822.00000,16,88,2,474.44000,2.28571,12.57143,286.92234,1.92760
5,12823.00000,221,297,5,351.90000,31.57143,42.42857,191.12371,1.28400
6,12826.00000,362,366,7,210.67429,51.71429,52.28571,131.66943,0.88458
7,12827.00000,38,45,3,143.38333,5.42857,6.42857,181.13361,1.21689
8,12828.00000,127,131,6,169.78500,18.14286,18.71429,198.69579,1.33487
9,12829.00000,23,361,2,138.11000,3.28571,51.57143,2.80551,0.01885
10,12830.00000,134,172,6,870.88250,19.14286,24.57143,820.01344,5.50900
11,12832.00000,65,99,2,191.51500,9.28571,14.14286,136.05034,0.91401
12,12836.00000,252,312,4,653.21500,36.00000,44.57143,305.13050,2.04992
13,12838.00000,340,374,2,341.56500,48.57143,53.42857,99.51499,0.66856
14,12839.00000,364,368,14,399.38714,52.00000,52.57143,433.81198,2.91443
15,12840.00000,82,227,4,681.69250,11.71429,32.42857,204.86143,1.37630
16,12841.00000,367,372,25,160.89400,52.42857,53.14286,290.06631,1.94872
17,12842.00000,238,309,2,542.77500,34.00000,44.14286,178.57732,1.19972
18,12843.00000,198,265,8,212.78250,28.28571,37.85714,173.18963,1.16352
19,12844.00000,101,131,2,162.98000,14.42857,18.71429,100.24893,0.67349

In [60]:
rfm_cltv_2_task_12months.head(20)

,Customer ID,recency_cltv_p,T,frequency,monetary_avg,recency_weekly_p,T_weekly,clv,scaled_cltv
0,12747.00000,366,370,11,381.45545,52.28571,52.85714,3698.38114,2.26075
1,12748.00000,372,374,210,153.82814,53.14286,53.42857,23623.99689,14.44088
2,12749.00000,209,214,5,814.48800,29.85714,30.57143,6538.82768,3.99706
3,12820.00000,323,327,4,235.58500,46.14286,46.71429,1204.32622,0.73618
4,12822.00000,16,88,2,474.44000,2.28571,12.57143,3029.79454,1.85205
5,12823.00000,221,297,5,351.90000,31.57143,42.42857,2085.98885,1.27512
6,12826.00000,362,366,7,210.67429,51.71429,52.28571,1444.88055,0.88323
7,12827.00000,38,45,3,143.38333,5.42857,6.42857,1888.15775,1.15419
8,12828.00000,127,131,6,169.78500,18.14286,18.71429,2124.46518,1.29864
9,12829.00000,23,361,2,138.11000,3.28571,51.57143,30.72005,0.01878
10,12830.00000,134,172,6,870.88250,19.14286,24.57143,8829.20916,5.39712
11,12832.00000,65,99,2,191.51500,9.28571,14.14286,1440.75875,0.88071
12,12836.00000,252,312,4,653.21500,36.00000,44.57143,3333.12403,2.03747
13,12838.00000,340,374,2,341.56500,48.57143,53.42857,1090.59559,0.66666
14,12839.00000,364,368,14,399.38714,52.00000,52.57143,4764.39200,2.91238
15,12840.00000,82,227,4,681.69250,11.71429,32.42857,2220.01235,1.35705
16,12841.00000,367,372,25,160.89400,52.42857,53.14286,3187.67091,1.94856
17,12842.00000,238,309,2,542.77500,34.00000,44.14286,1947.98231,1.19076
18,12843.00000,198,265,8,212.78250,28.28571,37.85714,1886.24684,1.15303
19,12844.00000,101,131,2,162.98000,14.42857,18.71429,1069.22242,0.65359

# # As the estimated period increases, the difference in expected income increases. There is a directly proportional relationship between the two

1. According to 6-month CLTV for 2010-2011 UK customers, you can put all your customers into 3 groups (A,B,C) and add to the dataset  
- Analyze the 3 groups for other variables in the data set

In [61]:
rfm_cltv_3_task=rfm.merge(cltv,on="Customer ID",how="left")

In [62]:
rfm_cltv_3_task=ggf.customer_lifetime_value(bgf,
                                   rfm['frequency'],
                                   rfm['recency_weekly_p'],
                                   rfm['T_weekly'],
                                   rfm['monetary_avg'],
                                   time=6,  # 6months
                                   freq="W",  # T's frequency info.
                                   discount_rate=0.01)

In [63]:
rfm_cltv_3_task=rfm_cltv_3_task.reset_index()

In [64]:
rfm_cltv_3_task.sort_values(by="clv").head(20)

      Customer ID      clv
2380  17850.00000  0.00000
1079  15107.00000  0.80661
1829  16725.00000  1.12937
2407  17912.00000  1.84031
1437  15881.00000  2.65599
947   14813.00000  3.03037
1214  15422.00000  3.33221
20    12845.00000  4.34974
1515  16048.00000  4.73538
1862  16792.00000  6.39550
292   13452.00000  7.23437
1134  15224.00000  8.17540
1725  16499.00000  9.05497
2304  17691.00000  9.09230
1995  17062.00000  9.11077
1433  15869.00000  9.20547
1681  16405.00000  9.21484
1139  15235.00000 10.54573
1454  15920.00000 11.80748
2440  17991.00000 12.27619

In [65]:
scaled3=scaler.fit_transform(rfm_cltv_3_task[["clv"]])

In [66]:
rfm_cltv_3_task["scaled_cltv"]=scaled3

In [67]:
task3_last=rfm_cltv_3_task.sort_values(by="scaled_cltv",ascending=False).head(20)

In [68]:
task3_last["segment"]=pd.qcut(gorev3_last["scaled_cltv"],3,labels=["C","B","A"])

NameError: name 'gorev3_last' is not defined

In [69]:
task3_last["scaled_cltv"].astype(int)

2486    99
589     64
2184    56
2213    42
1804    29
406     29
587     29
1173    27
133     26
1057    24
1485    24
692     24
1378    21
2499    20
2377    18
454     17
2150    16
2424    16
1503    15
139     15
Name: scaled_cltv, dtype: int64

In [70]:
task3_last.head(20)

      Customer ID         clv  scaled_cltv
2486  18102.00000 85651.01047    100.00000
589   14096.00000 55650.64677     64.97372
2184  17450.00000 48533.31011     56.66403
2213  17511.00000 36797.00673     42.96156
1804  16684.00000 25083.02541     29.28515
406   13694.00000 25060.70871     29.25909
587   14088.00000 25010.05913     29.19996
1173  15311.00000 23591.38948     27.54362
133   13089.00000 22927.69296     26.76874
1057  15061.00000 21123.08206     24.66180
1485  16000.00000 21110.80764     24.64747
692   14298.00000 20839.63143     24.33086
1378  15769.00000 18526.06343     21.62971
2499  18139.00000 17817.89132     20.80290
2377  17841.00000 15717.33660     18.35044
454   13798.00000 14629.74945     17.08065
2150  17389.00000 14028.56200     16.37875
2424  17949.00000 13819.55167     16.13472
1503  16029.00000 13594.32494     15.87176
139   13098.00000 13449.72336     15.70294